# Main configuration file for bounty

# Minimum amount a player can set a bounty for.

minimum-amount: 1000

# Maxiumum amount a player can set a bounty for.

maximum-amount: 100000000

# Cooldown for adding a bounty to a player in seconds.

bounty-cooldown: 600
